module.exports.errorCodes = {
  VALIDATION_ERROR_CODE: 400,
  LOGIN_ERROR_CODE: 401,
  INVALID_OWNERSHIP_ERROR_CODE: 403,
  NOT_FOUND_ERROR_CODE: 404,
  EMAIL_DUPLICATION_ERROR_CODE: 409,
  ANOTHER_ERROR_CODE: 500,
};
